version: "3"

tasks:
  venv:
    cmds:
      - python3 -m venv .venv

  install:
    cmds:
      - source .venv/bin/activate && python3 -m pip install --upgrade pip
      - source .venv/bin/activate && python3 -m pip install -r requirements.txt --progress-bar off

  build:
    cmds:
      - source .venv/bin/activate && dbt deps
      - source .venv/bin/activate && dbt seed
      - rm -rf jaffle-data
      - source .venv/bin/activate && dbt run
      - source .venv/bin/activate && dbt test

  setup:
    cmds:
      - task: venv
      - task: install
      - task: build
